---
centos_ntp_server: "{{ secret_ntp_server }}"
centos_http_proxy: "http://{{ secret_http_proxy_host}}:{{ secret_http_proxy_port }}"
centos_https_proxy: "http://{{ secret_https_proxy_host}}:{{ secret_https_proxy_port }}"
centos_timezone: "{{ timezone }}"